### ISSUE TITLE
less texty homepage

### ISSUE THREAD

**Issue by streamerd** [demo-verse/expressions-of-peace#10]
dapp's current homepage contains a lot text.  

more multimedia, story teller videos needed. 

we need to be going to a multi-page site for that.

**Comment by streamerd** [comment]
currently created this doc for how to structure the page for multi-page.
https://github.com/demo-verse/expressions-of-peace/blob/main/TODOs/refine-homepage.md

soon we will create a Google docs for those to articulate and collaborate on that better with 
@Roscalion.  He will be dropping a docs link soon ;) 

It's to prepare the page and kickstart the refinement effort, and before going into translation to other langs, we'll get more collaboration and reviews from other members, such as @AL0YSI0US , @docxology , @thetwosents and @simond110 and well, more.

**Comment by Roscalion** [comment]
[https://docs.google.com/document/d/1SMP9_qFV_R_ZZeIeFKJjNgxVHcaxh4GvI8Uzbg_dugQ/edit?usp=sharing](Google Docs - Project Planning Link)

**Comment by rsaunders-tech** [comment]
[Google Docs - Project Planning Link](https://docs.google.com/document/d/1SMP9_qFV_R_ZZeIeFKJjNgxVHcaxh4GvI8Uzbg_dugQ/edit?usp=sharing)

**Comment by AL0YSI0US** [comment]
This looks good friend. My car was broken into...I'm sleeping in it at a
friend's house...hoping to get the window repaired before rain comes. I am
sending you care.

**Comment by streamerd** [comment]
As-is, It's a bit too technical, texty and not all stuff gotta be on a single page, and it's like not ending on mobile, a lot text. for such detail and deeper dive, created a gitbook on the side.

There are a few parts we'd like to see there at first glance, and more discovered and accessed through navigation bar and as linked to its own page. 

What comes to mind are:

**Directly on the page:**
- An intro film, maybe max 5 minutes, explaining what, how and why kind of stuff.
- similarly, a story telling from some of existing or a fictional character/persona, that used their right and experienced this decentralised diplomacy paradigm.
- a few illustrations for interactions between stakeholders,
-make a few links and communities more visible.
- peace family (orgs that are supporting and we are including their knowledge, infra and inspired from)
- some links (eg. communities, socials, short paper/gitbook etc)

**Going into their own pages:**
- peacemakers that'd like to be there, with their testimonials/experience/thoughts on project,  and more about them, if cool.
- all links
- resources
- manifesto
- design considerations/principles
- about (what, why, how kind of stuff can be here I guess, but something like about better be on very intro too. )
 
+++ 
Please suggest some good designs and content-wise suggestions, as well as any collaborator on the writing, design and fim making is utmost desired.
